version: '3.9'

services:
  postgres-server:
    image: postgres:latest
    restart: always

    environment:
      POSTGRES_MULTIPLE_DATABASES: main-reserv1,admin main-reserv2,admin
      POSTGRES_DB: main
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    
    ports:
      - "5432:5432"
    volumes:
      - ./init-another-postgresql-databases.sh:/docker-entrypoint-initdb.d/init-another-postgresql-databases.sh